[package]
name = "res_mgr_web"
version = "0.1.0"
authors = ["sun <sun@yineng.com>"]
edition = "2021"

# [lib]
# crate-type = ["cdylib", "rlib", "dylib"]

[dependencies]
pi_assets = "0.14"
pi_share = "0.4"
serde = "1.0"
serde_json = "1.0"
pi_time = "0.5"

wasm-bindgen = "*"
js-sys = "0.3"


# [features]
# # default = ["no_debug", "no_define_js"]
# # default = ["create_class_by_str"]
# # default = ["no_debug", "share/rc"]
# default = ["debug"]
# # default = ["share/rc", "ecs/runtime"]
# # default = ["debug", "no_debug"]
# debug = ["share/rc", "ecs/runtime"]
# no_debug = []
# no_define_js = []
# create_class_by_str = []


[patch.crates-io]
pi_share = {path = "../../pi_share"}
pi_assets = {path = "../../pi_assets"}