
[package]
name = "gui"
version = "0.1.0"
authors = ["wzjsun <530739162@qq.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2"
share = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
idtree = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
flex_layout = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
ecs = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
ecs_derive = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
enum_default_macro = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
deque = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
slab = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
util = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
map = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
atom = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master", features = ["serde"]}
hash = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
heap = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
pointer = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
ucd = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
data_view = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
debug_info = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
dirty = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
densevec = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
res = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
cross_performance = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}
rectangle-pack = "0.4.2"
guillotiere = {version="*"}
# time: 3407.7350000152364
# vConsole.js:3 now: 3408.0800000810996
# vConsole.js:3 timediff: 0.6900000153109431
# vConsole.js:3 time: 3408.795000053942
# vConsole.js:3 now: 3409.1900000348687
# vConsole.js:3 timediff: 0.7850000401958823
# vConsole.js:3 time: 3409.925000043586
# vConsole.js:3 now: 3410.2800000691786
# vConsole.js:3 timediff: 0.6949999369680882
# vConsole.js:3 time: 3411.2850000383332
# vConsole.js:3 now: 3411.8550000712276
# vConsole.js:3 timediff: 0.9299999801442027
# vConsole.js:3 time: 3412.57000004407
# vConsole.js:3 now: 3412.914999993518
# vConsole.js:3 timediff: 0.6799999391660094
pi_spatial = "0.5"
pi_slotmap = "0.1"
pi_null = "0.1"
pi_link_list = "0.1"


color = { git = "https://github.com/GaiaWorld/pi_math.git", branch="master", features = ["serde"]}
bincode = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="master"}


# polygon = { git = "https://github.com/GaiaWorld/pi_math.git"}
# cg2d = { git = "https://github.com/GaiaWorld/pi_math.git"}
# color = { git = "https://github.com/GaiaWorld/pi_math.git", features = ["serde"] }
# cgmath = { git = "https://github.com/GaiaWorld/pi_math.git", features = ["serde"]}
# collision = { git = "https://github.com/GaiaWorld/pi_math.git", features = ["serde"]}
# octree = { git = "https://github.com/GaiaWorld/pi_math.git"}
hal_core = {path="../hal_core", features=["serde"]}
hal_derive = {path="../hal_derive"}
num-traits = "0.2.6"
fnv = "1.0.6"
lazy_static = "*"
derive_deref = "1.0.2"
paste = "0.1"
serde = { version = "1.0", features = ["derive"] }
ordered-float = { version = "1.0", default-features = false }
fxhash = "0.2.1"
wasm-bindgen = "*"
nalgebra = {version = "0.32", features = ["serde", "serde-serialize"]}
parry2d = {version = "0.13", features = ["serde-serialize"]}
log="*"
smallvec={version = "1.8", features = ["serde"]}
getset="0.1"
bitvec={version = "1.0", features = ["serde"]}
polygon2 = "0.3"
pi_polygon = "0.1"
pi_cg2d = "0.3"
cssparser = "0.29"
pi_print_any="0.1"

[dependencies.web-sys]
version = "*"
features = [
	"WebGlRenderingContext",
	"WebGlBuffer",
	"WebGlVertexArrayObject",
	"WebGlShader",
	"WebGlProgram",
	"WebGlUniformLocation",
	"WebGlActiveInfo",
	"WebGlTexture",
	"WebGlRenderbuffer",
	"WebGlFramebuffer",
	"Window",
	"HtmlCanvasElement",
	"Document",
	"CanvasRenderingContext2d",
	"ImageData",
	"HtmlImageElement",
	"console",
]

[features]
default = ["warning"]
performance=["web"]
web = []
print = []
warning = []
statistics = []

