
[package]
name = "gui"
version = "0.1.0"
authors = ["wzjsun <530739162@qq.com>"]
edition = "2018"

[dependencies]
derive-deref-rs = "0.1"
pi_share = "0.4"
pi_assets = "0.14"
ahash = "=0.8.6"
postcard = {version = "1.0", features = ["use-std"]}
nalgebra = {version = "0.32", features = ["serde", "serde-serialize"]}
pi_atom = { version="0.5", features = ["serde", "lookup_by_hash"] }
pi_link_list = "0.1"
pi_null = "0.1"
pi_hash = "0.1"
pi_flex_layout = "0.2"
pi_style = {version = "=0.1.15", registry = "yn"}
bitflags = "1.2"
# share = { git="https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
idtree = { git="https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
flex_layout = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
ecs = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
ecs_derive = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
enum_default_macro = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
deque = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
slab = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
util = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
map = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
# atom = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface", features = ["serde"]}
hash = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
heap = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
pointer = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
ucd = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
data_view = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
debug_info = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
dirty = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
densevec = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
cross_performance = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
rectangle-pack = "0.4.2"
guillotiere = {version="*"}
# time: 3407.7350000152364
# vConsole.js:3 now: 3408.0800000810996
# vConsole.js:3 timediff: 0.6900000153109431
# vConsole.js:3 time: 3408.795000053942
# vConsole.js:3 now: 3409.1900000348687
# vConsole.js:3 timediff: 0.7850000401958823
# vConsole.js:3 time: 3409.925000043586
# vConsole.js:3 now: 3410.2800000691786
# vConsole.js:3 timediff: 0.6949999369680882
# vConsole.js:3 time: 3411.2850000383332
# vConsole.js:3 now: 3411.8550000712276
# vConsole.js:3 timediff: 0.9299999801442027
# vConsole.js:3 time: 3412.57000004407
# vConsole.js:3 now: 3412.914999993518
# vConsole.js:3 timediff: 0.6799999391660094
pi_polygon = "0.1"
pi_cg2d = "0.3"
pi_spatial = "0.5"
pi_slotmap = "0.1"
# pi_spatial = { git = "https://github.com/GaiaWorld/pi_math.git", branch="master"}
color = { git = "https://github.com/GaiaWorld/pi_math.git", branch="master", features = ["serde"]}
bincode = { git="https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}


# pi_polygon = { git = "https://github.com/GaiaWorld/pi_math.git"}
# pi_cg2d = { git = "https://github.com/GaiaWorld/pi_math.git"}
# color = { git = "https://github.com/GaiaWorld/pi_math.git", features = ["serde"] }
# cgmath = { git = "https://github.com/GaiaWorld/pi_math.git", features = ["serde"]}
# collision = { git = "https://github.com/GaiaWorld/pi_math.git", features = ["serde"]}
# octree = { git = "https://github.com/GaiaWorld/pi_math.git"}
hal_core = {path="../hal_core", features=["serde"]}
hal_derive = {path="../hal_derive"}
num-traits = "0.2.6"
fnv = "1.0.6"
lazy_static = "*"
derive_deref = "1.0.2"
paste = "0.1"
serde = { version = "1.0", features = ["derive"] }
ordered-float = { version = "3.0", default-features = false, features = ["serde"] }
fxhash = "0.2.1"
wasm-bindgen = "*"
log="*"
smallvec={version = "1.8", features = ["serde"]}
getset="0.1"
bitvec={version = "1.0", features = ["serde"]}
polygon2 = "0.3"
cssparser = "0.29"
pi_print_any="0.1"

[dependencies.web-sys]
version = "*"
features = [
	"WebGlRenderingContext",
	"WebGlBuffer",
	"WebGlVertexArrayObject",
	"WebGlShader",
	"WebGlProgram",
	"WebGlUniformLocation",
	"WebGlActiveInfo",
	"WebGlTexture",
	"WebGlRenderbuffer",
	"WebGlFramebuffer",
	"Window",
	"HtmlCanvasElement",
	"Document",
	"CanvasRenderingContext2d",
	"ImageData",
	"HtmlImageElement",
	"console",
]

[patch.yn]

[features]
default = ["warning"]
performance=["web"]
web = []
print = []
warning = []
statistics = []

[patch.crates-io]
pi_atom = {path = "D://0_rust/pi_atom"}
pi_share = {path = "../../pi_share"}
pi_assets = {path = "../../pi_assets"}
pi_flex_layout = {path = "D://0_rust/pi_flex_layout"}

