[package]
name = "gui"
version = "0.1.0"
authors = ["wzjsun <530739162@qq.com>"]

[dependencies]
wcs = { path = "../../pi_lib/wcs" }
wcs_macro = { path = "../../pi_lib/wcs_macro" }
cg = { path = "../../pi_math/cg" }
deque = {path="../../pi_lib/deque"}
slab = {path="../../pi_lib/slab"}
heap = {path="../../pi_lib/heap"}