
[package]
name = "gui"
version = "0.1.0"
authors = ["wzjsun <530739162@qq.com>"]

[dependencies]
ecs = { path = "../../pi_lib/ecs" }
ecs_derive = { path = "../../pi_lib/ecs_derive" }
enum_default_macro = {path = "../../pi_lib/enum_default_macro" }
cg2d = { path = "../../pi_math/cg2d" }
color = { path = "../../pi_math/color" }
cgmath = { path = "../../pi_math/cgmath" }
octree = { path = "../../pi_math/octree" }
collision = { path = "../../pi_math/collision" }
deque = {path="../../pi_lib/deque"}
slab = {path="../../pi_lib/slab"}
util = {path="../../pi_lib/util"}
map = {path="../../pi_lib/map"}
heap = {path="../../pi_lib/heap"}
pointer = {path="../../pi_lib/pointer"}
atom = {path="../../pi_lib/atom"}
ucd = {path="../../pi_lib/ucd"}
data_view = {path="../../pi_lib/data_view"}
debug_info = {path="../../pi_lib/debug_info"}
dirty = {path="../../pi_lib/dirty"}
hal_core = {path="../hal_core"}
hal_webgl = {path="../hal_webgl"}
polygon = {path="../../pi_math/polygon"}
num-traits = "0.2.6"
fnv = "1.0.6"
lazy_static = "*"
stdweb = "0.4.15"
stdweb-derive = "0.5.1"
webgl-rendering-context = "0.1.0"
derive_deref = "1.0.2"
paste = "0.1"

[features]
#default = ["web"]
#web = []