
[package]
name = "gui"
version = "0.1.0"
authors = ["wzjsun <530739162@qq.com>"]

[dependencies]
wcs = { path = "../../pi_lib/wcs" }
wcs_macro = { path = "../../pi_lib/wcs_macro" }
enum_default_macro = { path = "../../pi_lib/enum_default_macro" }
cg = { path = "../../pi_math/cg" }
deque = {path="../../pi_lib/deque"}
slab = {path="../../pi_lib/slab"}
vecmap = {path="../../pi_lib/vecmap"}
heap = {path="../../pi_lib/heap"}
pointer = {path="../../pi_lib/pointer"}
atom = {path="../../pi_lib/atom"}
num-traits = "0.2.6"
fnv = "1.0.6"
lazy_static = "*"
ucd = "0.1.1"
# stdweb = "0.4.15"
# stdweb-derive = "0.5.1"
# webgl-rendering-context = "0.1.0"