# [target.emscripten]
# link-args = ["-O3", 
#             "-s", "TOTAL_MEMORY=16777216", 
#             # "-s", "TOTAL_MEMORY=167772160", 
#             "-s", "ALLOW_MEMORY_GROWTH=0", 
#             "-s", "MALLOC=dlmalloc", 
#             "-s", "ELIMINATE_DUPLICATE_FUNCTIONS=1",
#             "-s", "ENVIRONMENT=web",
#             "-s", "INLINING_LIMIT=1",
#             ]