[package]
name = "gui_web"
version = "0.1.0"
authors = ["moyy <moyy@yineng.com>"]

[dependencies]
atom = {path="../../pi_lib/atom"}
data_view = {path="../../pi_lib/data_view"}
share = {path="../../pi_lib/share"}
ecs = {path="../../pi_lib/ecs"}
ecs_derive = { path = "../../pi_lib/ecs_derive" }
map = { path = "../../pi_lib/map" }
debug_info = { path = "../../pi_lib/debug_info" }
fx_hashmap = { path = "../../pi_lib/fx_hashmap" }
hal_webgl = {path="../hal_webgl"}
hal_core = {path="../hal_core"}
cg2d = { path = "../../pi_math_hal/cg2d" }
color = { path = "../../pi_math_hal/color" }
cgmath = { path = "../../pi_math_hal/cgmath" }
octree = { path = "../../pi_math_hal/octree" }
gui = {path="../gui", features = ["web"]} #, features = ["performance"]
stdweb = "0.4"
stdweb-derive = "0.5.1"
webgl-rendering-context = "0.1.0"
lazy_static = "1"
serde = { version = "1.0", features = ["derive"] }
paste = "0.1"
ordered-float = "1.0"

[profile.release]
lto = true
opt-level = "z"
panic = 'abort'
codegen-units = 1

# [profile.dev]
# debug = 2
# opt-level = 3

# [features]
# default = ["no_debug", "no_define_js"]
# no_debug = []
# no_define_js = []