[package]
name = "hal_core"
version = "0.1.0"
authors = ["moyy <moyy@yineng.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pi_share = "0.4"
pi_atom = "0.5"
ordered-float = "3.0"
serde = { version = "1.0", features = ["derive"], optional = true }
log = "0.4"