[package]
name = "hal_core"
version = "0.1.0"
authors = ["moyy <moyy@yineng.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
share={path="../../pi_lib/share"}
ordered-float = "1.0"