[package]
name = "css_serialize"
version = "0.1.0"
authors = ["sun <530739162@qq.com>"]

[dependencies]
gui = {path="../gui"}
bincode = { git = "https://github.com/GaiaWorld/pi_lib.git"}
fx_hashmap = { git = "https://github.com/GaiaWorld/pi_lib.git"}
stdweb = "0.4.15"