[package]
name = "hal_webgl"
version = "0.1.0"
authors = ["moyy <moyy@yineng.com>"]

# [lib]
# crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pi_atom = "0.5"
pi_share = "0.4"
slab = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
deque = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
hash = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}
debug_info = { git = "https://github.com/GaiaWorld/pi_lib.git", branch="new_gui_interface"}

hal_core = { path = "../hal_core"}

ordered-float = "3.0"
wasm-bindgen = {version="*", features = ["serde-serialize"]}
js-sys = "*"
log ="*"


[dependencies.web-sys]
version = "*"
features = [
	"WebGlRenderingContext",
	"WebGlBuffer",
	"WebGlVertexArrayObject",
	"WebGlShader",
	"WebGlProgram",
	"WebGlUniformLocation",
	"WebGlActiveInfo",
	"WebGlTexture",
	"WebGlRenderbuffer",
	"WebGlFramebuffer",
	"console"
]

# [features]
# frame_stat = []  # 统计每帧信息的feature
[patch.crates-io]
pi_atom = {path = "D://0_rust/pi_atom"}
pi_share = {path = "../../pi_share"}